#!/usr/bin/python3
"""This is Exxeption Handling"""


try:
    print(x)
except:
    print("An exception occurred")
